feat(plot): add Path object into target in callback_info and callback_sched
tier4/CARET_analyze pull request #106
Opened 2022-08-08 03:48 UTC by atsushi421

[複数の Callback を入力に取るメソッドに Path オブジェクトを対応させること](https://tier4.atlassian.net/browse/T4PB-16448) の作業が完了したので、ご確認をお願いいたします。
以下の型を入力として受け付けられるように変更しました。
```
[callback_sched]
Union[Application, Executor, Path, Node, CallbackGroup, List[CallbackGroup]]

[callback_info]
Union[Application, Executor, Path, Node, CallbackGroup, CallbackBase, List[CallbackBase]]
```

テストコードを添付させていただきます。
- [テストコード(.ipynb)](https://drive.google.com/file/d/1JtsYTBD9alTaqf3XuzaXxlGpQq2ibbYU/view?usp=sharing)
- [使用したアーキテクチャファイル](https://drive.google.com/file/d/13wfDcJYNHAmiDcbQ49QqasNjjam7GvvY/view?usp=sharing)
- [使用したトレースデータ](https://drive.google.com/file/d/1qGGwnfWEYO9s0VUzt_Ap8jpsI0mSUXIU/view?usp=sharing)

2022-08-08 10:37 UTC, hsgwa requested changes

2022-08-08 10:37 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +        return list(cbgs), target.path_name
こちら、なるべくパスの順で表示してくれた方が良いと思います。
一意で順番も考慮させるためのクラスとしてUniqueListというのがあるので、これを利用してください。
https://github.com/tier4/CARET_analyze/blob/e1ba4e517fc79e87f2515dbcdbdd9c4bcf532539/src/caret_analyze/record/column.py#L112

1. 今record配下にあるUniqueListはcommon配下に移動
2. setで一意にしている箇所はUniqueListに変更し、Pathのノード順でコールバックを表示させるようにする。

2022-08-08 23:57 UTC, atsushi421 commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +        return list(cbgs), target.path_name
> こちら、なるべくパスの順で表示してくれた方が良いと思います。 一意で順番も考慮させるためのクラスとしてUniqueListというのがあるので、これを利用してください。
> 
> https://github.com/tier4/CARET_analyze/blob/e1ba4e517fc79e87f2515dbcdbdd9c4bcf532539/src/caret_analyze/record/column.py#L112
> 
> 1. 今record配下にあるUniqueListはunique_list.pyとしてcommon配下に移動
> 2. setで一意にしている箇所はUniqueListに変更し、Pathのノード順でコールバックを表示させるようにする。

1, 2 の修正が完了いたしました。
ご確認をお願いいたします。

2022-08-10 07:09 UTC, hsgwa approved these changes
LGTM

2022-08-10 07:09 UTC, merged