chore: rename 'jitter' to 'period' in Plot
tier4/CARET_analyze pull request #107
Opened 2022-08-08 04:04 UTC by atsushi421

Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>

[CARET_analyze で jitter としてしまった箇所を period に統一する](https://tier4.atlassian.net/browse/T4PB-19289) の作業が完了したので、ご確認をお願いいたします。
作業としては、機械的に jitter を period にリネームしただけです。

テストコードを添付させていただきます。
- [Yano環境の出力結果](https://drive.google.com/file/d/1CpPPN9zb2llZGi9aE4omely4Wp4-MAVS/view?usp=sharing)
- [テストコード(ipynb)](https://drive.google.com/file/d/1SrlN7QVh6dICg4v0IQ9wBYGMUXPw8stx/view?usp=sharing)
- [使用したアーキテクチャファイル](https://drive.google.com/file/d/1dRInIE2HquYziQ-qLakVL3_nAyrUMeh5/view?usp=sharing)
- [使用したトレースデータ](https://drive.google.com/file/d/1hALgv-iwjy54nJ_M_W3f0Kgkvc0OlEEx/view?usp=sharing)

2022-08-08 09:11 UTC, hsgwa commented
@atsushi421 
まだユーザーは多くはないですが、一応元の関数もdeprecatedで使える状態で残していただいても良いでしょうか？
以下のような実装です。

```
    def create_callback_jitter_plot(*args, **kargs):
        # warn('create_callback_jitter_plot is deprecated. Use create_callback_period_plot')
        create_callback_period_plot(*args, **kargs)
```

2022-08-08 09:11 UTC, hsgwa requested changes
@atsushi421 
まだユーザーは多くはないですが、一応元の関数もdeprecatedで使える状態で残していただいても良いでしょうか？
以下のような実装です。

```
    def create_callback_jitter_plot(*args, **kargs):
        # warn('create_callback_jitter_plot is deprecated. Use create_callback_period_plot')
        create_callback_period_plot(*args, **kargs)
```

2022-08-08 23:55 UTC, atsushi421 commented
@hsgwa 
チェックありがとうございます。
create_callback_jitter_plot を使えるように修正しました。
ご確認をお願いいたします。

2022-08-10 07:05 UTC, hsgwa approved these changes
LGTM!

2022-08-10 07:05 UTC, merged