(WIP)feat: add API to plot topic_info
tier4/CARET_analyze pull request #108
Opened 2022-08-08 07:03 UTC by atsushi421

Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>

[トピックの通信のレイテンシ、送信/受信周期、通信間隔の描画をサポートする](https://tier4.atlassian.net/browse/T4PB-19177) チケットの作業を行っています。
一旦、クラス構造の雛形を記述しています。

2022-08-09 00:11 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/pub_sub_info_interface.py
> +        pass  # TODO
PubSubTimeSeriesPlotを継承したインスタンスの使い方が定義されていれば十分ですので、
抽象クラスのコンストラクタまで引数は定義していただかなくて大丈夫です。

2022-08-24 09:59 UTC, hsgwa requested changes

2022-08-24 09:59 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/util.py
> +    po_dfs = [po.to_dataframe() for po in plot_objects]
ここ、to_dataframeがNaNを返すケースがあります。
NaNが含まれると後のmin/maxでエラーになってしまうので、remove_dropped=Trueとしてください。

```suggestion
    po_dfs = [po.to_dataframe(remove_dropped=True) for po in plot_objects]
```

2022-08-24 11:08 UTC, hsgwa commented on src/caret_analyze/runtime/application.py
> +                sorted(subs, key=lambda x: x.topic_name))
こちら、get_communicationsを利用してください。

2022-08-24 11:20 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/util.py
> +            return ColorSelectorPubSub()
ちょっとココは過剰な気もします。
get_colorの引数を増やしたり減らしたりする都度、全クラスに修正が必要になります。

これぐらいであれば、
1. ColorSelectorのコンストラクタにcoloring_rule引数を追加し、self._coloring_ruleとして保存
2. get_color_hashでself._color_ruleに応じてreturn
として１クラスにまとめてあげた方が良い気がします。

2022-08-24 11:25 UTC, hsgwa requested changes
すみません、
変更量が大きいので、少しずつコメントさせてください。

2022-08-25 01:41 UTC, atsushi421 commented
レビューして頂き、ありがとうございます。
お手すきの際にチェックして頂いて大丈夫です。
自分も都度更新させていただきます

2022-08-29 12:33 UTC, hsgwa commented on src/caret_analyze/runtime/application.py
> +                sorted(subs, key=lambda x: x.topic_name))
@atsushi421 
リマインドのためコメントいたします。
こちら、get_pub_subsの中身の実装が改善できるかと思います。
対応のほどよろしくお願いします。

2022-08-30 23:23 UTC, atsushi421 commented on src/caret_analyze/runtime/application.py
> +                sorted(subs, key=lambda x: x.topic_name))
こちら、get_communications を使用するように変更しました。
https://github.com/tier4/CARET_analyze/pull/108/commits/25db6b541c9463aa1fd012ae28602b528263771b

一旦 Application クラスの関数のままにしたのですが、移動先としてはどのクラスが適切でしょうか

2022-08-30 23:28 UTC, atsushi421 commented on src/caret_analyze/plot/bokeh/util.py
> +            return ColorSelectorPubSub()
ミーティングでお話した通り、callback_sched と time line を描画する場合の ColorSelector を分けました。
https://github.com/tier4/CARET_analyze/pull/108/commits/e0c32dbc7eb6ae13e5176279f813b81fe9e7a1f2

callback_sched の ColorSelector は元あった callback_sched.py 内に戻し、time line 描画用の ColorSelector は plot_util.py に置きました。

2022-08-30 23:29 UTC, atsushi421 commented
@hsgwa 
対応が遅くなり申し訳ありません。
一旦、指摘していただいた事項を修正しましたので、ご確認をお願いいたします。
リファクタリングは別の PR を出させて頂く予定です。

2022-08-31 05:43 UTC, hsgwa commented on src/caret_analyze/runtime/application.py
> +                sorted(subs, key=lambda x: x.topic_name))
だいぶスッキリしました！
ここまできたら、get_publishes, get_subscriptionsで分けて頂いた方が良いですね。

2022-08-31 07:52 UTC, hsgwa requested changes
手元で試した際に以下のエラーがでました。
```
IndexError: single positional indexer is out-of-bounds
```
確認をお願いできますでしょうか？

https://drive.google.com/drive/folders/18Pgw3btCGoQgvVNP6MlV0AdUUbQRjWrE?usp=sharing

それと、get_pub_subsを、get_publishers, get_subscriptionsに分割もお願いしたいです。

2022-08-31 08:52 UTC, atsushi421 commented
@hsgwa 
エラー対応と、get_publishers, get_subscriptionsへの分割が完了しました。
現状の実装だと、描画に時間がかかるので、リファクタリングの際に効率が悪い実装 (get_earliest_timestamp() など)も修正しようと思います。

2022-08-31 09:19 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/communication_info_interface.py
> +                f'{comm.summary["subscirbe_node"]}')
こちらtypoしています
```suggestion
                f'{comm.summary["subscribe_node"]}')
```

2022-08-31 09:19 UTC, hsgwa requested changes
あとtypoだけ修正をお願いします。

> 現状の実装だと、描画に時間がかかる
共有したデータですと、もしかするとto_dataframeで時間がかかっているのかもしれません。

2022-08-31 12:05 UTC, atsushi421 commented
value_objects/communication.py の段階から typo していたので、合わせて修正させて頂きました。

2022-09-01 00:00 UTC, merged