callback_sched
tier4/CARET_analyze pull request #14
Opened 2021-12-15 09:40 UTC by bopeng-saitama

2021-12-15 23:20 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +    target_node=app.get_node(target_name)
インターフェースの変更理由：
target_nameが存在しないノードの場合、get_nodeで例外が発生します。
そうすると「callback_schedが例外を出した」となり、動作が追いにくくなってしまうかと思います。

2021-12-15 23:23 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +                   duration_s: Optional[float] = None):
ここは以下のように変更をお願いします。
```
def callback_sched(
  target: Union[Node, CallbackGroup, Executor],
  lstrip_s: float=0,
  rstrip_s: float=0):
```

変更理由：
- **.callbacksを持ったインターフェースに揃える
- 無くても良い引数は無くす
- 他のapiと揃えるために、lstrip_s(スタートから無視する時間）rstrip_s（終了から無視する時間）にしてます。

2021-12-15 23:23 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +     elif type == 'executor':
ここはisinstance(target, Callback) などで型チェックをしてください。

2021-12-15 23:25 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +    # # 以下のように、型を見て分岐するイメージ。
ここのコメントは削除して頂いて構いません。

2021-12-15 23:25 UTC, hsgwa requested changes
コメントを追加しました。確認をお願いします。

2021-12-16 08:58 UTC, bopeng-saitama commented on caret_analyze/plot/bokeh/callback_sched.py
> +                   duration_s: Optional[float] = None):
修正しました。ご確認お願いいたしました。

2021-12-16 11:54 UTC, hsgwa requested changes
一部importでのエラーがあったのと、lstrip/rstripは対応をお願いします。

2021-12-16 11:54 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +from bokeh.application.application import Callback
手元の環境で試した所この箇所でエラーになります。

2021-12-16 11:54 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +        dataframe.append(callback.to_dataframe())
lstrip_sとrstrip_sはココで使ってください。
https://github.com/tier4/CARET_analyze/blob/f589f3173ef8fbf61eea849032eac31987f0af6c/caret_analyze/runtime/path_base.py#L79

2021-12-16 11:54 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +        dataframe.append(callback.to_dataframe())
単純な関数の仕様についてですが、
```
ret = get_**(arg)
```
という関数があった場合、
①argの値はget_**内で変更せず、②取得結果を返す、という動作を期待することが多いかと思います。

ここでは、dataframeを引数から削除し、get_frame内でリストを生成するようにしてください。
ちなみにリスト内包表記を使うと一行でかけます。
```
return [target.to_dataframe(lstrip_s=lstrip, rstrip_s=rstrip_s) for target in  targets]
```

2021-12-16 11:54 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +from typing import  Union
使っていないモジュールや、重複しているモジュールがあるようです。
まだCIを入れていないので特に警告などは出ていないですが、
ament_flake8を使うとコーディングスタイルをチェックしてくれます。
（他のモジュールでも、まだisort関連の警告はまだ直していないですので、今は完璧にしなくても結構です）
vscodeからスタイルをチェックすると開発がしやすいです。

2021-12-16 12:34 UTC, bopeng-saitama commented on caret_analyze/plot/bokeh/callback_sched.py
> +        dataframe.append(callback.to_dataframe())
大変勉強になりました。ありがとうございます。後で修正いたします。

2021-12-20 05:09 UTC, hsgwa approved these changes
確認しました。問題無さそうですのでマージ致します。

2021-12-20 05:10 UTC, merged