add: get cb_info_df and show timeline in bokeh visualization
tier4/CARET_analyze pull request #16
Opened 2022-02-16 04:32 UTC by atsushi421

2022-02-16 06:35 UTC, hsgwa requested changes
とりあえず気になった所をいくつか書きました。
確認をお願いします。

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +def get_cb_freq_with_timestamp(timestamp_df, initial_timestamp, callback_name='') -> pd.DataFrame:
確認ですが、callback_nameはオプションで意図通りでしょうか？
指定が必要であればデフォルト値は入れないほうが混乱しない気がしました。

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +    return callbacks
`No new end line`として警告が出ています。
ament_flake8などのツールを使って、コーディングスタイルを統一するようにお願いします。
(setup.bashを叩くと、ament_**で色々なツールが使えるようになります。

ここはまだCIに対応していないので、各々手作業でお願いしている状況です・・

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +def get_callbacks_from_names_list(app : Application , callback_names_list : List[str]) -> List[CallbackBase]:
ここは、Application/Node/CallbackGroup/Executorのクラスに`get_callbacks`を入れても良いかなと考えていました。
https://github.com/tier4/CARET_analyze/blob/main/caret_analyze/runtime/application.py#L515

例えば↓みたいなインターフェースをイメージしています。
```
def get_callbacks(self, callback_names: Tuple[str, ...]) -> List[CallbackBase]:
```

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +        except:
全てキャッチするとpython側の例外もキャッチして握りつぶしてしまいます。
エラー（中断）か警告（とりあえず継続）かはまだ整理しきれていないですが、
ここはコールバックが見つからない場合は例外をそのまま上位に伝えるようにしてください。
中断にすると後の処理ができないですが、何が悪いかをすぐに気づけますし、
警告にすると後の処理を進められますが、何が悪いか気づきにくいです。

もしcaret内部のエラーをキャッチしたい場合はhttps://github.com/tier4/CARET_analyze/blob/main/caret_analyze/exceptions.py#L16
で定義している、Errorをキャッチするようにしてください。

ここの場合、３種類がCARETからエラーが飛ぶようになっています。
https://github.com/tier4/CARET_analyze/blob/main/caret_analyze/runtime/application.py#L531
-  引数がおかしいとき
- 一つも見つからない時
- 複数見つかった時

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +            print(f"[Error] Failed find '{callback_name}'.")
ログ出力をする場合は、ログレベルなど確認できるように、以下のようにloggerを使ってください。
https://github.com/tier4/CARET_analyze/blob/9264960b1a07a08144e48cbc03fa453969e00eeb/caret_analyze/architecture/architecture_loaded.py#L562

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/cb_info_timeline.py
> +    p = figure(height=300, width=1000, title=title)
スクロールで横軸だけズームイン／ズームアウトできるようになっていると嬉しいです。
こちらを参考に、xwheel_zoomを有効にしてください。

https://github.com/tier4/CARET_analyze/blob/9264960b1a07a08144e48cbc03fa453969e00eeb/caret_analyze/plot/bokeh/callback_sched.py#L105

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/cb_info_timeline.py
> +    p.add_layout(p.legend[0], 'right')
具体的な指摘箇所が定まらないのですが、ここに。

パット見た感じ
- DataFrameのtimestamp/valueが何を指しているのか、
- グラフの縦軸と横軸が何を指しているのか、
というのが分かりにくいかなと思いました。

グラフの縦軸横軸のタイトル追加（特に単位）と、
DataFrameはcallback_start_timestamp[s]とperiod[ms]等に変えてみてはいかがでしょうか？

2022-02-16 06:35 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +        callback_latency_df[(callback_name, 'timestamp')] = latency_table[callback_name + '/callback_start_timestamp']  # start_timestamp で良いか要確認
時間としてはstart_timestampで良いと思います。
今の所仮置きのAPIで対処していますが、時系列データの時刻はsimtimeにも対応されていると良いと思います。
https://github.com/tier4/CARET_analyze/blob/707c6a892492dc6dd6a1c776380fa81ca7dd1df7/caret_analyze/plot/bokeh/callback_sched.py#L122

2022-02-16 08:50 UTC, takam5f2 commented on caret_analyze/plot/bokeh/callback_info.py
> +    return callbacks
CI適用しましょう。

2022-02-25 04:33 UTC, atsushi421 commented
@hsgwa
お疲れ様です。
Review で指摘していただいた事項の修正及び、オブジェクト指向プログラミングへのリファクタリングが完了したので、ご確認をお願いいたします。
共通化できる処理は、TimeSeriesPlot クラスのメソッドとして定義しました。

以下は動作検証の結果です。
https://drive.google.com/drive/folders/1QVrcwMOy8w_ZW-LXj5bV2q6g6N0ghPAN?usp=sharing

2022-02-25 04:36 UTC, atsushi421 commented on caret_analyze/plot/bokeh/callback_info.py
> +    return callback_jitter_df.dropna()  # 最も低周期の callback (index の長さが最も短い列) に合わせる
こちらは、show 関数内で、1つのコールバックの dataframe 毎に dropna を実行するように変更しました。

2022-02-25 04:37 UTC, atsushi421 commented on caret_analyze/plot/bokeh/callback_info.py
> +        callback_latency_table = callback.to_dataframe() * 10**(-9)  # [ns] -> [s]
可視化時にも timestamp の単位は [ns] を使用しました

2022-02-25 04:38 UTC, atsushi421 commented on caret_analyze/plot/bokeh/callback_info.py
> +def get_cb_freq_with_timestamp(timestamp_df, initial_timestamp, callback_name='') -> pd.DataFrame:
デフォルト値は削除いたしました

2022-02-25 04:39 UTC, atsushi421 commented on caret_analyze/plot/bokeh/callback_info.py
> +    return callbacks
編集した全てのファイルで ament_flake8 テストをパスしました

2022-02-25 04:40 UTC, atsushi421 commented on caret_analyze/plot/bokeh/callback_info.py
> +def get_callbacks_from_names_list(app : Application , callback_names_list : List[str]) -> List[CallbackBase]:
こちら、すでに実装されていた get_callback 関数を参考に実装させていただきました

2022-02-28 04:02 UTC, atsushi421 commented
@hsgwa 
[こちらのスラック](https://emb4hq.slack.com/archives/C017YM4AA06/p1646008461980789?thread_ts=1645430031.211369&cid=C017YM4AA06) で指摘していただいた事項の修正が完了しました。
show_* 関数の修正に伴って、_show_core メソッドを介さない実装に変更しました。

以下は動作検証の結果です。
https://drive.google.com/drive/folders/1_CDSo4xoOzSp-TOVZU7_hhe0GFxY6wI2?usp=sharing

2022-03-01 05:47 UTC, hsgwa requested changes
後で忘れないようにTODOのコメントだけ追加お願いします。

2022-03-01 05:47 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +        earliest_timestamp = latency_table.iloc[0].min()
例外やログはこれから整理するので、こちらにコメントでTODOを残して頂けるとありがたいです
```
# TODO: Emit an exception when latency_table size is 0.
```

2022-03-01 05:47 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_info.py
> +            if len(initial_timestamp) == 1:
こちらも同様にお願いします。

```
# TODO: Emit an exception when latency_table size is 0.
```

2022-03-01 06:25 UTC, merged