test: adapt humble flake8
tier4/CARET_analyze pull request #171
Opened 2022-10-27 06:32 UTC by keita1523

Adapt humble flake8.

Signed-off-by: keita1523 <keita.miura@tier4.jp>

2022-10-27 11:09 UTC, hsgwa requested changes

2022-10-27 11:09 UTC, hsgwa commented on src/caret_analyze/record/frequency.py
> +        Set a constructor.
Could you replace sentence as follows?

```suggestion
        Construct an instance.
```

2022-10-27 11:17 UTC, keita1523 commented on src/caret_analyze/record/frequency.py
> +        Set a constructor.
@hsgwa 
I modified it all.

2022-10-28 01:46 UTC, hsgwa approved these changes
LGTM

2022-10-28 01:46 UTC, merged