feat(lttng): add exception when file is not found
tier4/CARET_analyze pull request #172
Opened 2022-10-27 12:39 UTC by hsgwa

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>found

2022-10-28 19:00 UTC, keita1523 requested changes

2022-10-31 06:11 UTC, hsgwa commented on src/test/infra/lttng/test_lttng.py
> +            Lttng('')
I removed this case because bt2 function raises other exceptions.

2022-10-31 06:13 UTC, hsgwa commented on src/caret_analyze/infra/lttng/lttng.py
> +            raise FileNotFoundError(f'Failed to found {trace_dir}')
fixed: [5317edb](https://github.com/tier4/CARET_analyze/pull/172/commits/5317edb4869090d7269151c9992e194343093794)

2022-10-31 11:09 UTC, keita1523 approved these changes
@hsgwa 
LGTM

2022-11-01 04:27 UTC, takeshi-iwanari approved these changes
LGTM

2022-11-01 04:27 UTC, merged