timer event visualization
tier4/CARET_analyze pull request #18
Opened 2022-03-03 02:37 UTC by bopeng-saitama

2022-03-03 05:26 UTC, hsgwa requested changes
テストがいくつか失敗しているので確認をお願いします。
この機能の追加にあたってクラスのインターフェースにも修正を加えているため、Mockの追加定義が必要です。

2022-03-03 06:04 UTC, bopeng-saitama commented
> テストがいくつか失敗しているので確認をお願いします。 この機能の追加にあたってクラスのインターフェースにも修正を加えているため、Mockの追加定義が必要です。

承知いたしました。修正します。

2022-03-07 06:34 UTC, hsgwa requested changes
コメントの追加などお願いします。

2022-03-07 06:34 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> +                        if res > 500000:
ここの500000がマジックナンバーになっているので、
以下のように”何の数字なのか”がわかるようコメントを追加お願いします。

```
delayed_th = 500000
# この値を超えたらコールバックが遅延していると判定する ←英語で
```

2022-03-07 06:34 UTC, hsgwa commented on caret_analyze/plot/bokeh/callback_sched.py
> -    p.yaxis.visible = False
ここは1, 2, ...といったyaxisの値には特に意味は無いので、非表示で良いと思っていますがあえて表示に変えたのでしょうか？

2022-03-07 06:34 UTC, hsgwa commented on caret_analyze/value_objects/node.py
> +            msg += f'topic_name: {timer_period}'
ここのメッセージの修正をお願いします。
```
timer_period: {timer_period}
```

2022-03-07 07:09 UTC, hsgwa approved these changes
LGTM

2022-03-07 07:09 UTC, merged