verify_trace_points
tier4/CARET_analyze pull request #19
Opened 2022-03-17 10:55 UTC by keita1523

@hsgwa 
caret/rclcppで提供されているトレースポイントが入っているかを確認する機能
確認方法は以下
- プロセス内通信の場合
  - Pub側：`ros2:rclcpp_intra_publish`があるか確認
  - Sub側：`ros2:dispatch_intra_process_subscription_callback`があるか確認
- プロセス間通信の場合
  - Pub側：ros/rclcppのトレースポイントで足りるため確認不要
  - Sub側：`ros2:dispatch_subscription_callback`があるか確認

本機能はwarningを出すだけに留まる

2022-03-17 11:23 UTC, hsgwa requested changes

2022-03-17 11:23 UTC, hsgwa commented on test/runtime/test_path.py
> +        arch = Architecture('yaml', '/home/emb4/.ros/tracing/arch_universe_gsm8.yaml')
ここが、環境依存になってしまっています。
今はまだ厳密にカバレッジ等を使って管理等していないほどに、テストをしっかりとしていない状況です。
ですので、一旦はココのテストコード消していただいても良いと思います。

もし書くのであれば、データに依存しない形でモック等を使ってテストコードを書く必要が有ります。

2022-03-17 11:23 UTC, hsgwa commented on caret_analyze/infra/lttng/records_provider_lttng.py
> +    def verify_trace_points(
この関数はrecords_provider_lttngの外に出す意図は無いので、`_verify_trace_points`とリネームをお願いします。

2022-03-18 03:47 UTC, keita1523 commented on test/runtime/test_path.py
> +        arch = Architecture('yaml', '/home/emb4/.ros/tracing/arch_universe_gsm8.yaml')
テストコードは削除致しました。

2022-03-18 03:47 UTC, keita1523 commented on caret_analyze/infra/lttng/records_provider_lttng.py
> +    def verify_trace_points(
リネーム致しました。

2022-03-18 04:07 UTC, keita1523 commented
コメント対応致しました。
チケットにテスト結果などを載せております。
https://tier4.atlassian.net/browse/T4PB-15635

2022-03-22 10:42 UTC, hsgwa commented
LGTM

2022-03-22 10:42 UTC, merged