refactor(plot): refactor callback scheduling
tier4/CARET_analyze pull request #240
Opened 2023-01-13 02:26 UTC by atsushi421

## Description
This PR refactors `callback_sched` in Plot package.

## Related links
- JIRA ticket: https://tier4.atlassian.net/browse/T4PB-24805
- To reproduce: https://drive.google.com/drive/folders/1ir_2ixQzZkjzo_PP_PYj3BUO-exyRQko?usp=share_link

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-01-16 23:34 UTC, hsgwa requested changes
Here are some comments.
I think the behavior is good, but I had some concerns about the implementation.

2023-01-17 22:49 UTC, atsushi421 commented on src/caret_analyze/plot/visualize_lib/bokeh/color_selector.py
> +            callback name, by default ''
Fixed in https://github.com/tier4/CARET_analyze/pull/240/commits/16a01e5cf1223c890b2725c199c149e15f3c726b.

2023-01-17 22:49 UTC, atsushi421 commented on src/caret_analyze/plot/visualize_lib/bokeh/color_selector.py
> +            return ColorSelectorNode()
Fixed in https://github.com/tier4/CARET_analyze/pull/240/commits/44c20e991c87e520f0c4219117ae3f7480a62a95.

2023-01-17 22:50 UTC, atsushi421 commented on src/caret_analyze/plot/visualize_lib/bokeh/color_selector.py
> +    def create_instance(coloring_rule: str):
Addressed in https://github.com/tier4/CARET_analyze/commit/44c20e991c87e520f0c4219117ae3f7480a62a95.

2023-01-17 22:51 UTC, atsushi421 commented on src/caret_analyze/plot/callback_scheduling/callback_scheduling_plot.py
> +                raise InvalidArgumentError('target.callback_groups is None')
Fixed in https://github.com/tier4/CARET_analyze/pull/240/commits/472b091e771ea7eef2ed01f171f207ff7517d7e7.

2023-01-17 22:51 UTC, atsushi421 commented on src/caret_analyze/plot/callback_sched.py
> +    logger.warning("The 'callback_sched' interface is deprecated, "
Fixed in https://github.com/tier4/CARET_analyze/pull/240/commits/f20dec5ea98449d0ca7a71417f1ed1ebeee44948.

2023-01-23 03:56 UTC, hsgwa approved these changes
LGTM!

2023-01-23 04:47 UTC, merged