feat/diff_node_names
tier4/CARET_analyze pull request #245
Opened 2023-01-20 08:16 UTC by taro-yu

Signed-off-by: yu-taro- <milktea1621@gmail.com>

## Description

Implemented diff_node_names

## Related links
https://tier4.atlassian.net/browse/T4PB-18417

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-02-05 15:21 UTC, taro-yu commented
- Add class Diff.
- Function diff_nodes_names implemented using set.
- Add test with mocker.

2023-02-06 02:46 UTC, rokamu623 commented
@taro-yu 
For basic matters,
- Please follow the rules of commit message (e.g., feat:, fix:, etc.)
- Please --signoff when you do commit.
- Please merge main into this commit.

2023-02-06 03:12 UTC, rokamu623 requested changes
Here are some comments on the entire implementation.

- Do not use `@staticmethod`.
  - For easier tests
```
def diff_node_names(self, arch1, arch2):
  diff = Diff(arch1, arch2)
  return diff.diff_node_names
```
- Create a new py file for `Diff class`.
- Please also address the minor problems commented below.

2023-02-06 03:12 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +        assert name1 == name2
The type of the variable patched in `node_names` is incorrect.
The type of `node_names` is `Tuple[str]`, but the type of `hoge` is `str`.

2023-02-06 03:12 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +        assert name1 == name2
Please add the following test pattern.
- node name only in node_mock
- node name only in node_mock2

2023-02-06 03:12 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +        assert name1 == name2
On the right side of `assert`, write the expected correct value.

in this case,
```
assert name1 == ('hoge', )
```

2023-02-06 03:12 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +        node_mock2 = mocker.Mock(spec=Architecture)
This is not mock of NodeStruct.
Please change the naming.

ex)
- architecture_mock0

2023-02-06 06:50 UTC, rokamu623 requested changes
The problem as a whole is described here.

- [ ] Please do not use `@staticmethod`.
```
def diff_by_nodes(arch1, arch2):
  return Diff(arch1, arch2).diff_by_nodes
```
- [ ] Please create a class for the Diff test.

2023-02-06 07:58 UTC, rokamu623 requested changes

2023-02-06 07:58 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +        inter_arch1_arch2 = set_arch1 & set_arch2
- [ ] It appears to be a redundant description.

```suggestion
        inter_arch1_arch2 = set(arch1.node_names) & set(arch2.node_names)
```

2023-02-20 06:18 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +        inter_arch1_arch2 = set_arch1 & set_arch2
After discussion, it is determined that the current implementation is acceptable.

2023-02-21 09:23 UTC, taro-yu commented
@rokamu623 
add diff_node_topics/pubs/subs/callbacks() and make mock tests for these  funcs.

2023-02-22 02:47 UTC, rokamu623 requested changes

2023-02-22 02:47 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def diff_node_topics(
This function compares all topic in Architecture.
Therefore, the name of this function should be,
```suggestion
    def diff_topic_names(
```

DiffArchitecture.diff_node_topics, too.

2023-02-22 02:47 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +                            ('drive_node', 'actuator_dummy_node'))
Use an abstract name.
ex) `node1`

2023-02-22 02:47 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +        name1, name2 = Architecture.diff_node_names(architecture_mock1, architecture_mock2)
For the entire test code:

The return value of the function is multiple names of node .
Please make sure that this is evident from the naming.

An example is as follows:
```suggestion
        node_names_in_mock1, node_names_in_mock2 = Architecture.diff_node_names(architecture_mock1, architecture_mock2)
```

2023-02-22 03:29 UTC, rokamu623 requested changes

2023-02-22 03:29 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +               topic_2 == ('topic4', 'topic3')
In order to adapt to any order, how about the following implementation?

```suggestion
        assert sorted(topic_2) == sorted(('topic3', 'topic4'))
```

2023-02-22 07:45 UTC, taro-yu commented
@rokamu623 
Review points have been corrected. 
Please check.

2023-02-24 00:50 UTC, rokamu623 approved these changes
LGTM!

2023-02-24 03:20 UTC, rokamu623 requested changes

2023-02-24 03:20 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def diff_node_names(
doc string must be described (for each function).

Reference:
https://github.com/tier4/CARET_analyze/blob/f17cd5b74af6d12398e356809368dade5e856675/src/caret_analyze/architecture/architecture.py#L397-L408

2023-02-25 02:39 UTC, taro-yu commented
@rokamu623 
Add doc string for the five diff functions.
please check.

2023-03-04 05:18 UTC, taro-yu commented
@rokamu623 
move DiffNode class in architecture,.py to node.py

2023-03-14 14:46 UTC, taro-yu commented on src/caret_analyze/architecture/architecture.py
> +    def diff_node_callbacks(
@takam5f2 
remove the diff_callbacks func and the test codes about it.

2023-03-20 06:31 UTC, rokamu623 commented on src/test/architecture/test_architecture.py
> +class TestDiff:
Fixed it in https://github.com/tier4/CARET_analyze/pull/245/commits/c2055136072541d7d00fe85d0dad0d23cf08b5d4 .

2023-03-20 06:32 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def diff_node_callbacks(
fixed it in https://github.com/tier4/CARET_analyze/pull/245/commits/e595a3cb36c63bd79b3d39d986d22a58ebdd582c .

2023-03-20 06:35 UTC, taro-yu commented
@takam5f2 

> @taro-yu Could you add the comment I suggested? This implementation should be temporal in this moment.

added TODO comment in node.py

2023-03-20 09:21 UTC, rokamu623 requested changes
docstring should be revision in 2 point each 3 function.

2023-03-20 09:21 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +        the node names that exist only in the respective architectures.
For all docstring:

The explanation is redundant.

```suggestion
        Compare two architecture objects and return the difference of nodes name.
```

2023-03-20 09:21 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +
For all docstring:

The "Returns" field is missing.

Reference: 
https://github.com/tier4/CARET_analyze/blob/main/src/caret_analyze/architecture/combine_path.py#L46

2023-03-22 00:22 UTC, rokamu623 approved these changes
LGTM!

2023-03-22 03:26 UTC, merged