refactor(plot): refactor message flow
tier4/CARET_analyze pull request #267
Opened 2023-03-20 05:40 UTC by atsushi421

## Description
This PR refactors message flow.

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-03-29 01:21 UTC, rokamu623 requested changes
There is no loss of functionality due to refactoring.
It has been checked both from the source code and from actual behaviour.

One point is raised below.
However, this point is trivial and I rely on the @atsushi421  to decide whether it needs to be corrected.

2023-03-30 21:25 UTC, atsushi421 commented on src/caret_analyze/plot/visualize_lib/bokeh/message_flow_source.py
> +                row_values = [converter.convert(_) for _ in row_values]
Since `_` explicitly specifies the name of the variable for this line only (which will not be used later), I do not make any changes.

2023-03-31 00:16 UTC, atsushi421 commented
@takeshi-iwanari
A review of this within EmbIV has been completed.
Could you please review it?

2023-03-31 04:34 UTC, takeshi-iwanari approved these changes
LGTM!

@atsushi421 
You have plan to delete `message_flow_old` ,  right?
I'll modify CARET_report to use `Plot.create_message_flow_plot()` today or tomorrow.

2023-03-31 07:16 UTC, atsushi421 commented
@takeshi-iwanari 
Yes, I plan to remove it. Thank you for your cooperation.

One more point, please correct the use of the `export_path` argument in CARET_report to use the `save()` method.
https://github.com/tier4/CARET_report/blob/a00a35d891fa55bfec6e0d0204216daa7047bab9/report/analyze_path/analyze_path.py#L171
The `export_path` argument will also be removed in the near future.

2023-03-31 07:39 UTC, rokamu623 approved these changes
LGTM!

2023-03-31 07:40 UTC, merged

2023-03-31 09:36 UTC, takeshi-iwanari commented
@atsushi421 

> I'll modify CARET_report to use Plot.create_message_flow_plot() today or tomorrow.

- Done (will be merged soon)
- I found one minor issue that y axis scroll is disabled with the new `Plot.create_message_flow_plot`

2023-04-05 04:44 UTC, atsushi421 commented
@takeshi-iwanari 
Thank you for your report. 
I have submitted a PR for a correction, can you review it?
https://github.com/tier4/CARET_analyze/pull/274