feat(plot): draw callback latency at fitst and last in chain_latency
tier4/CARET_analyze pull request #293
Opened 2023-05-15 11:38 UTC by atsushi421

## Description
This PR fixes to draw callback latencies at the first and last for `chain_latency`.

## Related links
- Ticket: 
- To reproduce: 

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-05-30 03:12 UTC, rokamu623 requested changes
The calc_latency_from_path_df() function does not appear to be called from the outside.

2023-05-30 03:12 UTC, rokamu623 commented on src/caret_analyze/plot/graphviz/chain_latency.py
> +    def calc_latency_from_path_df(target_columns: list[str]) -> np.ndarray:
The `calc_latency_from_path_df()` function does not appear to be called from the outside.
```suggestion
    def _calc_latency_from_path_df(target_columns: list[str]) -> np.ndarray:
```

2023-05-30 03:12 UTC, rokamu623 commented on src/caret_analyze/plot/graphviz/chain_latency.py
> +            latency = calc_latency_from_path_df(first_cb_columns)
Same as above.
```suggestion
            latency = _calc_latency_from_path_df(first_cb_columns)
```

2023-05-30 03:12 UTC, rokamu623 commented on src/caret_analyze/plot/graphviz/chain_latency.py
> +            latency = calc_latency_from_path_df(last_cb_columns)
Same as above.
```suggestion
            latency = _calc_latency_from_path_df(last_cb_columns)
```

2023-06-01 00:17 UTC, rokamu623 commented on src/caret_analyze/plot/graphviz/chain_latency.py
> +            latency = calc_latency_from_path_df(last_cb_columns)
Because `calc_latency_from_path_df()` is an intra-functional function, it is kept secret from the outside world without `_`.

2023-06-01 00:17 UTC, rokamu623 approved these changes
LGTM!

2023-06-01 06:21 UTC, atsushi421 commented
@nabetetsu 
Could you please review this PR?

2023-06-05 01:03 UTC, nabetetsu approved these changes
LGTM :+1:

2023-06-05 04:41 UTC, merged