fix: fix check_ctf warning message
tier4/CARET_analyze pull request #308
Opened 2023-06-27 11:12 UTC by ymski

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-06-28 08:46 UTC, isp-uetsuki requested changes

2023-06-28 08:46 UTC, isp-uetsuki commented on src/caret_analyze/infra/lttng/event_counter.py
> +            # In this case, the measured application uses only intra process communication,
Minor improvement of comment.

```suggestion
            # In this case, the measured application uses only inter process communication,
```

2023-06-28 09:09 UTC, ymski commented on src/caret_analyze/infra/lttng/event_counter.py
>          # Here, only warnings are given.
I forgot to correct the position of the comment.
Fixed in [0505e60](https://github.com/tier4/CARET_analyze/pull/308/commits/0505e6014389544260a2d28a39e619498e4a776d)

2023-06-28 09:41 UTC, isp-uetsuki approved these changes
LGTM

2023-06-29 05:47 UTC, takeshi-iwanari approved these changes
I attached how warning is output for each version and each condition. Everything looks okay to me. Could you also confirm if they are as you intended?
If it's okay, we can merge it.

|CARET_trace|TraceData|caret/rclcpp|LD_PRELOAD|Result (Displayed warning)|Result|Note|
|:----|:----|:----|:----|:----|:----|:----|
|V0.4.11|caret_demos (no intra comm)|y|y|No Warning|OK|w/ v0.4.11: Failed to find trace point added by caret-rclcpp. **The original issue is fixed** |
|V0.4.11|caret_demos (no intra comm)|y|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.11|caret_demos (no intra comm)|n|y|No Warning|OK|w/ v0.4.11: Failed to find trace point added by caret-rclcpp. **Behavior changed but it's okay** |
|V0.4.11|caret_demos (no intra comm)|n|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.11|Autoware (has intra comm)|y|y|No Warning|OK|w/ v0.4.11: no warning because it has intra comm|
|V0.4.11|Autoware (has intra comm)|y|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.11|Autoware (has intra comm)|n|y|Failed to find trace points added by caret-rclcpp. If the application doesn't have any intra communication, please ignore this message. To check whether binary are built with caret-rclcpp, run CARET CLI : ros2 caret check_caret_rclcpp.|OK|w/ v0.4.11: Failed to find trace point added by caret-rclcpp.|
|V0.4.11|Autoware (has intra comm)|n|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.11|Autoware (has intra comm)+light|y|y|No Warning|OK|w/ v0.4.11: no warning because it has intra comm|
|V0.4.11|Autoware (has intra comm)+light|y|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.11|Autoware (has intra comm)+light|n|y|Failed to find trace points added by caret-rclcpp. If the application doesn't have any intra communication, please ignore this message. To check whether binary are built with caret-rclcpp, run CARET CLI : ros2 caret check_caret_rclcpp.|OK|w/ v0.4.11: Failed to find trace point added by caret-rclcpp.|
|V0.4.11|Autoware (has intra comm)+light|n|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.8|caret_demos (no intra comm)|y|y|No Warning|OK| |
|V0.4.8|caret_demos (no intra comm)|y|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.8|caret_demos (no intra comm)|n|y|Failed to find trace points added by caret-rclcpp. To check whether binary are built with caret-rclcpp, run CARET CLI : ros2 caret check_caret_rclcpp.|OK| |
|V0.4.8|caret_demos (no intra comm)|n|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.8|Autoware (has intra comm)+light|y|y|No Warning|OK|w/ v0.4.11: no warning because it has intra comm|
|V0.4.8|Autoware (has intra comm)+light|y|n|Failed to find trace point added by LD_PRELOAD|OK| |
|V0.4.8|Autoware (has intra comm)+light|n|y|Failed to find trace points added by caret-rclcpp. If the application doesn't have any intra communication, please ignore this message|OK|w/ v0.4.11: Failed to find trace point added by caret-rclcpp. To check whether binary are built with caret-rclcpp,run CARET CLI|
|V0.4.8|Autoware (has intra comm)+light|n|n|Failed to find trace point added by LD_PRELOAD|OK| |

2023-06-29 06:07 UTC, ymski commented
@takeshi-iwanari 

Thank you for validating the various cases.
The table you provided appears to be working as intended.

2023-06-29 06:35 UTC, merged