Add callback hist
tier4/CARET_analyze pull request #317
Opened 2023-08-24 01:57 UTC by emori-ctc

## Description
Complete the API to display the response time of a path in a histogram.
In addition, an API to display the latency of Node and Communication in a histogram will be implemented.

## Related links
Jira: https://tier4.atlassian.net/browse/RT2-886

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-08-31 02:35 UTC, rokamu623 requested changes
Reviewed by.
The following points should be corrected.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot.py
> +hist_types = list[Frequency | Latency | Period]
Type names (hist_types) must be capitalised.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot.py
> +
`hist_types` should be defined as `[Frequency | Latency | Period]`.

Because:
the type of **one** visualisation target is Latency et al.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot.py
> +    """Class that provides API for timeseries data."""
Update doc_string from the one for Timeseries to the one for Histogram.

There are several other similar mistakes.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot_factory.py
> +            Argument metrics is not "frequency", "latency", or "period".
Update doc_string from the one for Timeseries to the one for Histogram.

There are several other similar mistakes.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot_factory.py
> +        #     callback_names = [obj.column_names for obj in target_objects] # type: ignore
Erase unnecessary codes.

There are several other similar mistakes.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot_factory.py
> +                metrics_.append(frequency)
How about renaming the variables as follows?

- metrics -> metrics_name
- metrics_ -> metrics

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/plot_facade.py
> +# from collections.abc import Sequence
Erase unnecessary codes.

There are several other similar mistakes.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +        latencies: list[list[int]] = [
Latency is not the only thing stored in this variable. It should be renamed.

2023-08-31 02:35 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot_factory.py
> +                metrics_.append(latency)
`List Comprehensions` notation should be used.

ex)
```Python
odd = [int(num) for num in arr if num%2 == 1]
```

2023-08-31 05:56 UTC, rokamu623 requested changes
Please fix typo.

2023-08-31 05:56 UTC, rokamu623 commented on src/caret_analyze/plot/histogram/histogram_plot_factory.py
> +            Metrics for histogramplot data.
HistogramPlot

2023-09-01 06:01 UTC, rokamu623 requested changes
The following revisions are requested.

2023-09-01 06:01 UTC, rokamu623 commented on src/caret_analyze/plot/plot_facade.py
> +            parse_collection_or_unpack_for_hist(target_objects),  # type: ignore
Please do not use `# type: ignore`.

The same applies to `create_latency_histogram_plot`, and `create_period_histogram_plot`.

2023-09-04 01:40 UTC, rokamu623 requested changes
LGTM!

2023-09-04 01:41 UTC, rokamu623 approved these changes
LGTM!

2023-09-08 04:48 UTC, rokamu623 approved these changes
LGTM!

Request an operational test.

2023-09-18 21:52 UTC, rokamu623 approved these changes
LGTM!

2023-09-20 05:22 UTC, nabetetsu approved these changes
I have confirmed histogram was displayed as expected.
However, it is difficult to see when graphs overlap, so we would like to consider improvements for the future, such as devising a hover display.

![image](https://github.com/tier4/CARET_analyze/assets/86041052/d08ec40c-4af2-4703-92f3-65fbed580124)

2023-09-20 06:18 UTC, merged