feat: support iron useful tracepoints
tier4/CARET_analyze pull request #318
Opened 2023-08-24 08:25 UTC by ymski

## Description

This PR will implement the reading of useful trace points into CARET, which was added in iron.

The trace points added in iron are the following:
- ros2:ring_buffer_construct
- ros2:ring_buffer_enqueue
- ros2:ring_buffer_dequeue
- ros2:ring_buffer_clear
- ros2:buffer_to_ipb
- ros2:ipb_to_subscription

In addition, the following existing tracepoints have been modified for addition to rolling
- ros2_caret:caret_init

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-09-01 11:08 UTC, isp-uetsuki requested changes

2023-09-04 02:08 UTC, ymski commented on src/caret_analyze/infra/lttng/records_source.py
> +
This property was created to check the reading results and this is no longer used.
Removed in [5958c8b](https://github.com/tier4/CARET_analyze/pull/318/commits/5958c8bece1dcd1935068065326c0fc396b80621).

2023-09-05 07:28 UTC, isp-uetsuki requested changes

2023-09-06 08:40 UTC, isp-uetsuki approved these changes
LGTM

2023-10-04 03:33 UTC, nabetetsu approved these changes
LGTM :+1:

2023-10-04 09:57 UTC, merged