feat: stacked bar worst-in-input and all
tier4/CARET_analyze pull request #339
Opened 2023-09-14 03:10 UTC by rokamu623

## Description
implement 'worst-in-input' and 'all' option for stacked bar

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-09-14 08:25 UTC, bopeng-saitama requested changes

2023-09-14 08:25 UTC, bopeng-saitama commented on src/caret_analyze/record/records_service/response_time.py
> +                # if record dont has some timestamps,
```suggestion
                # if record doesn't have some timestamps,
```

2023-09-14 09:16 UTC, nabetetsu submitted a review, later dismissed
LGTM:+1:

Both `all` and `worst-in-input` option are well visualized as we expected.

![rt2-862 drawio](https://github.com/tier4/CARET_analyze/assets/86041052/bdc3c12d-3b90-4389-a67a-1b348ca3e880)

2023-09-15 03:58 UTC, bopeng-saitama approved these changes
LGTM

2023-09-15 05:08 UTC, nabetetsu approved these changes

2023-09-15 06:01 UTC, merged