feat: add regular expression function to get_callbacks().
tier4/CARET_analyze pull request #36
Opened 2022-05-10 09:21 UTC by kuboichiTakahisa

2022-05-24 00:16 UTC, hsgwa requested changes

2022-05-24 00:16 UTC, hsgwa commented on test/runtime/test_application.py
> +from defer import return_value
このパッケージは使っていますでしょうか？確認をお願いします。
自動で入られれた行に見えますので、不要なものでしたら削除をお願いします。

2022-05-24 00:16 UTC, hsgwa commented on caret_analyze/runtime/application.py
> +                logger = logging.getLogger('LoggingTest')
loggerの使い方については、他パッケージを参考に変更をお願いします。
https://github.com/tier4/CARET_analyze/blob/main/caret_analyze/architecture/architecture_loaded.py#L41

2022-05-24 00:16 UTC, hsgwa commented on caret_analyze/runtime/application.py
> +                print('error')
こちらはデバッグ用のprint文でしょうか？
loggerも使っているので、不要に見えます。

2022-05-26 09:04 UTC, hsgwa commented on caret_analyze/runtime/application.py
> +                print('error')
InvalidArgumentErrorのキャッチではなくErrorのキャッチに変更をお願いします。　

2022-06-09 09:14 UTC, hsgwa requested changes

2022-06-09 09:14 UTC, hsgwa commented on test/runtime/test_application.py
> +        assert app.get_callbacks('cb*') == [callback_mock0, callback_mock1]
?のケースもテストに追加をお願いします。

2022-06-09 09:14 UTC, hsgwa commented on test/runtime/test_application.py
> +    def test_get_callbacks(self, mocker: MockerFixture):
MockerFixtureは旧バージョンに対応するため使わないことにしました。削除をお願いします。

2022-06-09 09:14 UTC, hsgwa commented on test/runtime/test_application.py
> +        #define mocks
flake8の警告が出ています。

2022-06-09 09:38 UTC, hsgwa commented on test/runtime/test_application.py
> +        assert app.get_callbacks('cb*') == [callback_mock0, callback_mock1]
ex:
assert app.get_callbacks('*') == [callback_mock0, callback_mock1]
assert app.get_callbacks('cbb*') == []

2022-06-16 09:54 UTC, hsgwa commented
@kuboichiTakahisa 
こちらのPRですが、最新のmainブランチをマージ／リベースをお願いできないでしょうか？

2022-06-24 03:08 UTC, hsgwa commented on test/runtime/test_application.py
> +    def test_get_callbacks(self, mocker: MockerFixture):
@kuboichiTakahisa 
まだ残っているようですので、修正をお願いします。
https://github.com/tier4/CARET_analyze/runs/7018614821?check_suite_focus=true

2022-06-27 04:52 UTC, hsgwa commented on src/caret_analyze/common/util.py
> +import Levenshtein
新規パッケージのようですので、package.xmlにpython-levenshteinの追加をお願いできますでしょうか？

https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L2577

2022-06-27 06:13 UTC, hsgwa requested changes
flake8周りのエラーも出ているので対応お願いします。

pytestがrosdepのインストールで失敗しています。
以下のPRを適用すれば通るようになります。
https://github.com/tier4/CARET_analyze/pull/75

2022-06-27 06:13 UTC, hsgwa commented on src/caret_analyze/common/util.py
> +    def how_similar_str(name1: str, name2: str) -> bool:
- how_similar_str→calc_similarityへ名前の変更をお願いします。
- 戻り値の型はboolではなくてfloatかと思います。

2022-06-27 06:13 UTC, hsgwa commented on src/caret_analyze/runtime/application.py
> +            return Util.find_one(is_target_callback, self.callbacks)
ここらへんのtry-except分は冗長に見えます。
以下の関数にリファクタリングは出来ますでしょうか？
```
def Util.find_similar_one(target: str, key: Callable[[Any], str], items: Collection[Any], th: float = 0.8) -> Any:
```

```
get_callback():
  Util.get_similar_one(callback_name, lambda callback: callback.name, self.callbacks)
  # 必要があればtry-catch
```

2022-06-27 12:50 UTC, keita1523 commented on src/caret_analyze/runtime/application.py
> +                    msg = similarity = x.executor_name
Similarityを消す

2022-06-27 12:50 UTC, keita1523 commented on src/caret_analyze/runtime/application.py
> +                        'topic_name' + comm.topic_name
msgの中身がくっついた状態になる？

node = "node1"
msg = "publish_node" + node
msgは "publish_nodenode1"になるはず

2022-06-28 07:16 UTC, keita1523 commented on src/caret_analyze/common/util.py
> +import Levenshtein
requirements.txtを追加
legenshteinを記述しました。

2022-06-28 07:19 UTC, keita1523 commented on src/caret_analyze/common/util.py
> +    def how_similar_str(name1: str, name2: str) -> bool:
全置換で関数名を変更しました。
floatに変更しました。

2022-06-28 07:44 UTC, keita1523 commented on src/caret_analyze/runtime/application.py
> +                    msg = similarity = x.executor_name
消しました

2022-06-30 02:58 UTC, keita1523 commented on src/caret_analyze/common/util.py
> +    def warning_with_str(name1: str):
削除しました

2022-07-01 01:43 UTC, keita1523 commented on src/caret_analyze/runtime/application.py
> +            return Util.find_one(is_target_callback, self.callbacks)
リファクタリング完了しました。

2022-07-01 09:28 UTC, hsgwa requested changes
今途中とのことですが、一旦コメントを送ります。

2022-07-01 09:28 UTC, hsgwa commented on src/requirements.txt
> +statistics
statisticsは標準ライブラリのものでしょうか？標準ライブラリであれば不要かと思います。
https://docs.python.org/ja/3/library/statistics.html

2022-07-01 09:28 UTC, hsgwa commented on src/requirements.txt
> +levenshtein
levenshteinは使わないようであれば削除をお願いします。

2022-07-01 09:28 UTC, hsgwa commented on src/caret_analyze/common/util.py
> +    def calc_similarity(name1: str, name2: str) -> float:
calc_similarityはUtil以外から呼ぶことが無くなったので、不要そうであれば削除をお願いします。

2022-07-06 00:33 UTC, keita1523 commented on src/requirements.txt
> +levenshtein
削除しました。

2022-07-06 00:40 UTC, keita1523 commented on src/requirements.txt
> +statistics
他Embメンバーに下記コマンドを試してもらったところ、元環境には入っておらず、インストールされたそうです。そのため、残して置きたいと思います。
```
pip3 install statistics
```

2022-07-06 00:53 UTC, keita1523 commented on src/caret_analyze/common/util.py
> +    def calc_similarity(name1: str, name2: str) -> float:
削除しました。

2022-07-06 01:17 UTC, hsgwa requested changes

2022-07-06 01:17 UTC, hsgwa commented on src/caret_analyze/runtime/application.py
> +        if (len(node_paths) == 0):
node_pathsはreturnする変数ではないでしょうか？
returnが消えたままになっています。

2022-07-06 01:17 UTC, hsgwa commented on src/requirements.txt
> +statistics
pypiが提供しているstatisticsはpython2用のものではないでしょうか？
確認をお願いします。
> A port of Python 3.4 statistics module to Python 2.*, initially done through the [3to2 tool](https://pypi.python.org/pypi/3to2).

https://pypi.org/project/statistics/

2022-07-06 01:55 UTC, keita1523 commented on src/caret_analyze/runtime/application.py
> +        if (len(node_paths) == 0):
見落としてました。
Returnを追加致しました。

2022-07-06 02:05 UTC, keita1523 commented on src/requirements.txt
> +statistics
statisticsをuninstallしてもimport statisticsができたので、必要ありませんでした。
requriements.txtから削除しました。

2022-07-06 10:01 UTC, hsgwa approved these changes
LGTM!

2022-07-06 10:02 UTC, merged