fix: support for multimethod 1.10
tier4/caret_analyze pull request #398
Opened 2023-10-18 02:34 UTC by bopeng-saitama

## Description

support for multimethod 1.10.

## Related links

Jira: https://tier4.atlassian.net/browse/RT2-984

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-10-18 07:01 UTC, rokamu623 requested changes
If not causing errors, the following is desirable.

2023-10-18 08:23 UTC, bopeng-saitama commented on src/caret_analyze/record/record_factory.py
> +        columns: Sequence[ColumnValue]
Fixed it in https://github.com/tier4/caret_analyze/pull/398/commits/875b94ef737a887dd788cd0ff59c2c86217e474d.

2023-10-18 08:23 UTC, bopeng-saitama commented on src/caret_analyze/record/records_service/response_time.py
> +            worst_record = RecordFactory.create_instance(None)
Fixed it in https://github.com/tier4/caret_analyze/pull/398/commits/875b94ef737a887dd788cd0ff59c2c86217e474d.

2023-10-19 08:09 UTC, rokamu623 approved these changes
LGTM!

2023-10-20 08:02 UTC, xygyo77 approved these changes
Trace data (https://github.com/tier4/CARET_report/releases/download/20221227/autoware_launch_trace_20221227-150253_universe_rosbag.zip ) to check the message flow graphs.
The following four graphs were png'd and the hash values (sha256sum) were confirmed to match.
 - mrm_emergency_stop_operator -> vehicle_cmd_gate_0 (6c3844da83fb9023c20c6615e4b3d1000000f26b3ce5d156ecc6ea17ea283728)  
 - mrm_emergency_stop_operator -> vehicle_cmd_gate_1   (f9cfc40d317289aa63bb90f3d1a9f7b1211682270838bf0e244d302539c55171)  
 - mrm_emergency_stop_operator -> vehicle_cmd_gate_2   (7ff851d6f0c9253bce9e9138c57a0e49912334b7f2e73835f0eb5a614d98e4e6)
 - behavior_path_planner -> obstacle_avoidance_planner_0   (7c8bc3c2c809b19e00923e270bd1e14f364646f25d06a50c3a9acfb344c3acd5)

2023-10-23 07:18 UTC, merged