feat: Unified graph captions.
tier4/caret_analyze pull request #410
Opened 2023-10-27 03:30 UTC by emori-ctc

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-10-30 03:49 UTC, rokamu623 requested changes
As shown below, the `hoge case` is also displayed when `create_latency_timeseries` is visualised.
![bokeh_plot](https://github.com/tier4/caret_analyze/assets/48247817/1a2e857a-def7-44ec-bb19-f0d8b5ed42a7)
The same applies for `create_frequency_timeseries` and `create_period_timeseries`.
Resolve this issue.

We also list two additional trivial mistake as follow:

2023-10-30 03:49 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py
> +        title: str = f'Stacked bar of  Response Time --- {self._case} case ---'
Together with latency, etc., it should be lower-cased.
```suggestion
        title: str = f'Stacked bar of  response time --- {self._case} case ---'
```

2023-10-30 03:49 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/timeseries.py
> +            f'histogram of {data_type} --- {self._case} case ---'
```suggestion
        title: str = f'Timeseries of {data_type}'if self._case is None else\
            f'Timeseries of {data_type} --- {self._case} case ---'
```

2023-11-02 09:06 UTC, rokamu623 requested changes

2023-11-02 09:06 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py
> +        title: str = f'Stacked bar of response Time --- {self._case} case ---'
Not fixed.
```suggestion
        title: str = f'Stacked bar of response time --- {self._case} case ---'
```

2023-11-06 04:58 UTC, rokamu623 requested changes
Careless mistakes can still be found. Please fix.

2023-11-06 04:58 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +            if case is None else f'histogram of {data_type} --- {case} case ---',
```suggestion
            if case is None else f'Histogram of {data_type} --- {case} case ---',
```

2023-11-07 03:37 UTC, rokamu623 requested changes
It is not compatible with bokeh 3.x.

2023-11-07 03:37 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +            x_axis_label=x_label, y_axis_label='Probability', plot_width=800
```suggestion
            x_axis_label=x_label, y_axis_label='Probability', width=800
```

2023-11-08 04:32 UTC, rokamu623 submitted a review, later dismissed
LGTM!

2023-11-13 01:39 UTC, rokamu623 approved these changes
LGTM!

2023-11-13 02:57 UTC, xygyo77 approved these changes
LGTM
![stacked_bar_bokeh_plot](https://github.com/tier4/caret_analyze/assets/6880067/9c949a01-4904-4991-b4cd-7a53fc5053dc)

2023-11-13 04:34 UTC, merged