Feat: add sim time to plot APIs (only non-supported APIs)
tier4/caret_analyze pull request #433
Opened 2023-11-20 03:15 UTC by xygyo77

## Description
Modify the following API to support sim_time.

- create_response_time_stacked_bar_plot()
- create_response_time_timeseries_plot()
- create_response_time_histogram_plot()
- create_latency_histogram_plot()
- create_period_histogram_plot()
- create_frequency_histogram_plot()

## Related links
[https://tier4.atlassian.net/browse/RT2-1083](https://tier4.atlassian.net/browse/RT2-1083)

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-11-22 08:39 UTC, isp-uetsuki requested changes
- I suggest creating utility function to get `ClockConverter` from object (Communication, Callback, etc.) to recude redundancy. My suggestions are:
  - adding `util.py` to `caret_analyze/plot`
  - adding `get_clock_converter` function to `util.py` above
- I suggest adding simulation time support to `StackedBarPlot.to_dataframe`. (I think it does not work currently because `LatencyStackedBar.to_dataframe` does not support simulation time.)
- I suggest removing `MetricsBase._convert_timeseries_records_to_sim_time` and using conversion functionality of metrics objects (`Frequency`, `ResponseTime`, etc.) instead to reduce redundancy.

2023-11-24 02:35 UTC, xygyo77 commented on src/caret_analyze/plot/metrics_base.py
> +                    if isinstance(k, str)  # Skip unless k is of type str.
When "app.path"/"app._path" was specified for target_objects, both "system_time" would pass, but for "sim_time", an exception would occur when "app._path" was specified, so the direct cause of this problem was removed.

2023-11-24 02:46 UTC, xygyo77 commented on src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py
> +            apply_x_axis_offset(fig, frame_min, frame_max, x_range_name)
Acknowledged

2023-11-24 02:47 UTC, xygyo77 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +        x_label = x_label + label_str
Added to distinguish between system time and simulation time, but will be removed.

2023-11-24 02:58 UTC, xygyo77 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +        plot.legend.click_policy = 'hide'
Added because it is not possible to check when graph bars overlap, but removed because it is outside the scope of this ticket.

2023-11-24 04:12 UTC, xygyo77 commented on src/caret_analyze/plot/metrics_base.py
> +                    if isinstance(k, str)  # Skip unless k is of type str.
When "app.path"/"app._path" was specified for target_objects, both "system_time" would pass, but for "sim_time", an exception would occur when "app._path" was specified, so the direct cause of this problem was removed.

2023-11-24 04:14 UTC, xygyo77 commented on src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py
> +        data = self._updated_with_unit(data, ['start time'], 1e-9, converter)
The response time is assumed to be converted to sim_time by Latency.to_records() after this.
I understand about x_label.

2023-11-27 02:39 UTC, isp-uetsuki requested changes
- I think the meaning of `is_base_ts_convert` argument of `Frequency.to_records` is a little bit difficult to understand. I suggest to remove this argument by:
  - removing `converter` argument from `FrequencyTimeSeries._get_timestamp_range`. Now, `min_time` and `max_time` in `FrequencyTimeSeries.to_timeseries_records_list` are always in system time.
  - removing `is_base_ts_convert` argument of `Frequency.to_records` and `Frequency._get_frequency_with_timestamp`.

2023-11-27 06:28 UTC, xygyo77 commented on src/test/record/records_service/test_latency_records.py
> +        result = to_dict(latency.to_records())
Understood.

`        result = to_dict(latency.to_records(converter=create_converter.get_converter()))
`

2023-11-27 10:39 UTC, isp-uetsuki approved these changes
LGTM

2023-12-11 06:14 UTC, merged