fix: bokeh interger warning
tier4/caret_analyze pull request #447
Opened 2023-12-14 01:55 UTC by rokamu623

## Description
Changed implementation so that BokehUserWarning (out of range integer) is not generated.
Converted time difference from UnixTime to Time Difference by subtracting offset before giving array to bokeh.

## Related links
Jira: https://tier4.atlassian.net/browse/RT2-1071

## Notes for reviewers
Please check the following:
- implementation problem
- Are there any Warnings?
- Does the main and output match?
- pytest

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-12-14 05:49 UTC, isp-uetsuki requested changes

2023-12-14 06:37 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/util/util.py
> -    x_range_name: str = ''
Thank you for reviewed.
Fixed this pointed in [a5e5a6f](https://github.com/tier4/caret_analyze/pull/447/commits/a5e5a6f2783b6e495eb13da92cf2c0ad1a3f13bf).

2023-12-14 06:43 UTC, isp-uetsuki approved these changes
LGTM

2023-12-14 07:21 UTC, xygyo77 approved these changes
![image](https://github.com/tier4/caret_analyze/assets/6880067/266a1a15-c270-4f5c-8012-442e954d3dbf)
I have confirmed that the bokeh warnings in question are not output when drawing graphs.

LGTM

2023-12-15 07:05 UTC, bopeng-saitama approved these changes
LGTM
test result:
[test.pdf](https://github.com/tier4/caret_analyze/files/13682193/test.pdf)

2023-12-18 02:39 UTC, merged