Trace event order reversed
tier4/caret_analyze pull request #470
Opened 2024-01-30 02:35 UTC by miyakoshi-dev

## Description

addressing an issue where the order of trace events is reversed

## Related links

https://tier4.atlassian.net/browse/RT2-1245

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2024-02-19 10:30 UTC, isp-uetsuki requested changes

2024-02-29 02:15 UTC, miyakoshi-dev commented on src/caret_analyze/infra/lttng/id_remapper.py
> +                    if min_distance is None or min_distance > distance:
I fixed

2024-02-29 02:15 UTC, miyakoshi-dev commented on src/test/infra/lttng/test_lttng.py
> +            },
I fixed

2024-02-29 02:15 UTC, miyakoshi-dev commented on src/test/infra/lttng/test_lttng.py
> +
I fixed

2024-02-29 02:16 UTC, miyakoshi-dev commented on src/test/infra/lttng/test_lttng.py
> +            lttng.data.lifecycle_state_machines.df.iloc[1]['node_handle'] == 1
Cannot compare because timestamp does not exist

2024-03-04 06:29 UTC, isp-uetsuki approved these changes
LGTM

2024-03-04 06:58 UTC, xygyo77 approved these changes
![image](https://github.com/tier4/caret_analyze/assets/6880067/08bdad2c-3c04-455e-9aa1-088548a59751)

LGTM

2024-03-05 00:41 UTC, merged