fix: Histogram Improvement
tier4/caret_analyze pull request #475
Opened 2024-02-15 00:38 UTC by emori-ctc

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2024-02-15 04:32 UTC, rokamu623 requested changes
In particular, please be sure to address any changes regarding color.

2024-02-15 04:32 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +        colors = [
Please use `ColorSelector` (`ColorSelectorFactory`) to determine the color of the graph.

2024-02-15 04:32 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +            hist, bins = histogram(hist_type, 20, data_range, density=False)
Please make the variable names easy to understand.

e.g. `data`, `data_by_one_object`, `data_row`

2024-02-15 04:32 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +                quad = plot.quad(
Is it possible to make the `legend` of a histogram with no data (all elements are 0) transparent?

If you can't come up with an idea, I can support you.

2024-02-16 07:12 UTC, rokamu623 requested changes

2024-02-16 07:12 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +            colors.append(color_selector.get_color())
How about this implementation?
```suggestion
        color_selector = ColorSelectorFactory.create_instance('unique')
        colors = [color_selector.get_color() for _ in hists_t]
```

2024-02-16 08:42 UTC, rokamu623 requested changes

2024-02-16 08:42 UTC, rokamu623 commented on src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
> +        quad_dicts = {t: [] for t in target_objects}
There was an annotation omission in my suggestion.
```suggestion
        quad_dicts: dict[HistTypes, list[GlyphRenderer]] = {t: [] for t in target_objects}
```

2024-02-20 03:22 UTC, bopeng-saitama approved these changes
LGTM

2024-02-20 10:03 UTC, xygyo77 submitted a review, later dismissed
![image](https://github.com/tier4/caret_analyze/assets/6880067/e25e2d49-e3f2-4482-a6fc-21a0fd9ea60b)

LGTM

2024-02-28 02:35 UTC, rokamu623 approved these changes
LGTM!
and it is confirmed to works properly.
![image](https://github.com/tier4/caret_analyze/assets/48247817/563c57b5-d12a-41da-b882-6e6918533cb7)

2024-02-28 02:36 UTC, merged