speeding up by limiting registration to init_events
tier4/caret_analyze pull request #480
Opened 2024-02-28 05:30 UTC by miyakoshi-dev

## Description

speeding up by limiting registration to init_events

## Related links

https://tier4.atlassian.net/browse/RT2-1375

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] (Optional) The PR has been properly tested with CARET_report verification.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2024-02-29 07:16 UTC, isp-uetsuki requested changes

2024-02-29 07:16 UTC, isp-uetsuki commented on src/caret_analyze/infra/lttng/lttng_event_filter.py
`SameAddressFilter` is updated while applying filter, which cause problem when user use same `SameAddressFilter` instance to create multiple `Lttng` instances. I suggest following changes to avoid this problem.

- add `reset` method to `LttngEventFilter`

```
    def reset(self) -> None:
        pass
```

- override `reset` method in `SameAddressFilter`

```
    def reset(self) -> None:
        super().reset()
        self._list_construct_executor.clear()
        self._list_callback_group.clear()
```

- call `reset` of all event filters at the beginning of `_parse_lttng_data`

```
        if event_filters:
            for f in event_filters:
                f.reset()
```

2024-03-01 00:54 UTC, miyakoshi-dev commented on src/caret_analyze/infra/lttng/lttng_event_filter.py
Fixed

2024-03-01 00:54 UTC, miyakoshi-dev commented on src/caret_analyze/infra/lttng/lttng.py
> +            modified_event_filters or [],
Fixed

2024-03-01 00:55 UTC, miyakoshi-dev commented on src/caret_analyze/infra/lttng/lttng.py
> +# Copyright 2021 Research Institute of Systems Planning, Inc.
In my environment, Copyright was not corrected because it was ISP

2024-03-04 01:12 UTC, isp-uetsuki approved these changes
LGTM

2024-03-04 02:31 UTC, xygyo77 approved these changes
![image](https://github.com/tier4/caret_analyze/assets/6880067/fa99b67a-031e-441a-8448-3a43d743b83b)

LGTM

2024-03-05 00:18 UTC, merged