feat/rename_node_and_callback
tier4/CARET_analyze pull request #84
Opened 2022-07-13 05:47 UTC by rokamu623

callback, node, path, executor をrenameする機能を実装する。

現在は関数名のみ記述しています。

2022-07-13 05:49 UTC, rokamu623 commented
@takam5f2 
CARET_analyzeへのPR作成の方法はこれで合っておりますでしょうか？

2022-07-13 06:42 UTC, hsgwa commented
@rokamu623 
> CARET_analyzeへのPR作成の方法はこれで合っておりますでしょうか？
PR作成方法としては合っております。

まだマージ準備できていないようであれば、DarftPRに変えておくと良いです。
マージ準備できましたら、hsgwaをレビューワーにして頂けると幸いです。

2022-08-17 15:47 UTC, hsgwa requested changes

2022-08-17 15:47 UTC, hsgwa commented on src/caret_analyze/struct/__init__.py
> +# Copyright 2021 Research Institute of Systems Planning, Inc.
structクラスはarchitecture/infra/runtimeパッケージ横断的に使わないようにしておきたいです。
structクラスはarchitectureパッケージの内部のみで利用し、architectureパッケージの出力はvalueobjectsを期待しています。
structパッケージはarchitectureパッケージ配下に移動をお願いします。

2022-08-17 15:47 UTC, hsgwa commented on src/caret_analyze/runtime/callback.py
> +                      TimerCallbackStruct)
runtimeパッケージ配下のすべての*.pyはStructValueのままで、変更は不要です。

2022-08-17 15:47 UTC, hsgwa commented on src/test/infra/lttng/test_latency_definitions.py
> +from caret_analyze.struct import (
infra配下もStructValueそのまま変更無しでお願いします。

2022-08-17 15:47 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
>              return Util.find_one(lambda x: x.node_name == node_name, self.nodes)
Architectureクラスの出力はNodeStructValueのままでお願いします。
```suggestion
    def get_node(self, node_name: str) -> NodeStructValue:
        try:
            node = Util.find_one(lambda x: x.node_name == node_name, self.nodes)
            return node.to_value()
```
Architectureクラスの内部では変更可能のままにしつつ、出力される型は今までどおりStructValueです。
ほかの関数についても同様にお願いします。

2022-08-19 03:40 UTC, rokamu623 commented
Archtecture下以外のstructパッケージ参照を削除し、structパッケージをArchtecture直下に移動させました。
pytestでエラーが出ているのが少し気がかりです。チェックをお願いいたします。

2022-08-26 03:04 UTC, rokamu623 commented
一旦今日の作業分をpushしました。
NodePath周りでエラーが起きていますが、これはチケットの方で言及した、MessageContext周りに依るものだと思われます。

2022-08-29 12:28 UTC, hsgwa reviewed
取り急ぎいくつか気づいた所をコメントしておきます。
infraとruntimeパッケージ配下は今回のスコープ外です。
infraとruntimeディレクトリ以下のpythonスクリプトには変更が入らないようにお願いします。

2022-08-29 12:28 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +    def get_callback(self, callback_name: str) -> CallbackStruct:
こちらもto_valueを使いCallbackStructValueを返すようにしてください。

2022-08-29 12:28 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +        return Tuple(v.to_value() for v in self._communications)
大文字Tupleは型アノテーション用です。
タプル内包表記には`tuple(_.to_value() for _ in self._communications)`としてください。

2022-08-29 12:30 UTC, hsgwa commented
@rokamu623 
semantic-pull-requestも失敗しています。
PRのタイトルも適切に修正をお願いします
```
feat(architecture): support rename api
```

2022-08-31 01:55 UTC, rokamu623 commented
現状テストが動きません。

2022-08-31 08:14 UTC, hsgwa requested changes
スコープ外のファイルも変更していただいているのですが、軒並みflake8でエラー扱いされています。全て修正をお願いします。

graph_searchのテストについては、比較する場合はValueクラスで比較するよう変更してください。
```
assert node_path.to_value() == expected.to_value()
```

message context周りは今回確認しきれませんでした。まずは上記の対応をお願いします。

2022-08-31 08:14 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
>          return Util.find_one(lambda x: x.callback_name == callback_name, self.callbacks)
こちら戻り値の型は変えないようお願いします。
```suggestion
    def get_callback(self, callback_name: str) -> CallbackStructValue:
        callback = Util.find_one(lambda x: x.callback_name == callback_name, self.callbacks)
        return callback.to_value()
```

2022-08-31 08:14 UTC, hsgwa commented on src/caret_analyze/infra/interface.py
> +        callback_info : CallbackStructValueInfo
ここは元の実装が誤っていました。
実装と揃えてください。

```suggestion
        callback_info : CallBackStructValue
```

2022-08-31 08:14 UTC, hsgwa commented on src/caret_analyze/infra/interface.py
> +        variable_passing_info : VariablePassingStructValueInfo
こちらも同様に実装と揃えてください。

```suggestion
        variable_passing_info : VariablePassingStructValue
```

2022-08-31 08:14 UTC, hsgwa commented on src/caret_analyze/infra/lttng/bridge.py
ここは変更前に戻してください。

2022-08-31 08:14 UTC, hsgwa commented on src/caret_analyze/infra/lttng/bridge.py
こちらも修正前にもどしてください。

2022-08-31 08:14 UTC, hsgwa commented on src/caret_analyze/infra/lttng/bridge.py
> +            value.topic_name == StructValue_value.topic_name
こちらも修正前にもどしてください。

2022-08-31 08:14 UTC, hsgwa commented on src/caret_analyze/infra/lttng/records_provider_lttng.py
> +        comm_info : CommunicationStructValueInfo
こちらは元の実装が誤っていました。
変更していただけるのであれば、正しい方に直していただけると幸いです。
```suggestion
        comm_info : CommunicationStructValue
```

2022-09-02 02:59 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
>          return Util.find_one(lambda x: x.callback_name == callback_name, self.callbacks)
対応しました。
self.callbackの時点でTuple[CallbackStructValue]が返る実装になっているので、型指定だけ変更しました。

2022-09-02 02:59 UTC, rokamu623 commented on src/caret_analyze/infra/interface.py
> +        callback_info : CallbackStructValueInfo
対応しました。

2022-09-02 02:59 UTC, rokamu623 commented on src/caret_analyze/infra/interface.py
> +        variable_passing_info : VariablePassingStructValueInfo
対応しました。

2022-09-02 02:59 UTC, rokamu623 commented on src/caret_analyze/infra/lttng/bridge.py
対応しました。
恐らく、structを全検索した弊害であったと思います。

2022-09-02 02:59 UTC, rokamu623 commented on src/caret_analyze/infra/lttng/bridge.py
対応しました。

2022-09-02 03:00 UTC, rokamu623 commented on src/caret_analyze/infra/lttng/bridge.py
> +            value.topic_name == StructValue_value.topic_name
対応しました。

2022-09-02 03:00 UTC, rokamu623 commented on src/caret_analyze/infra/lttng/records_provider_lttng.py
> +        comm_info : CommunicationStructValueInfo
対応しました。

2022-09-02 03:09 UTC, rokamu623 reviewed
@hsgwa 
テストをto_valueで行ったりケアレスミスを行ったりして、エラーが若干減りました。
まだいくつかは残っているようです。

2022-09-02 03:09 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def named_paths(self) -> Tuple[PathStruct, ...]:
pathマネージャ周りの返り値はXXXStructValueではなくXXXStructが的確だと思い修正しました。

2022-09-05 00:06 UTC, hsgwa requested changes
flake8周りのエラーがまだ多くでているので、先に修正をおねがいします。

2022-09-05 00:17 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +    def named_paths(self) -> Tuple[PathStruct, ...]:
以下の行でPathStructに直すのが適切と考えたのでしょうか？
```
self._path_manager = NamedPathManager(loaded.paths)
```
コンストラクタで何を受け取るかについては特に考えてはいないなかったですが、
少なくとも、ArchitectureクラスのインターフェースはStructValue固定のままの修正が今回のrefactor段階です。

ですので、Architectureクラスの以下の箇所は変更前と同じ、PathStructValueに戻してください。
```
def add_path(self, path_name: str, path_info: PathStruct) -> None:
```

個人的には、NamedPathManager(loaded.paths)　のコンストラクタからto_valuesした物を入れるのが良いかなと思います。

2022-09-09 03:07 UTC, hsgwa commented
今のうちにコメントしておきますと、DCOチェックが失敗しています。
本PRが含んでいる全てのコミットに対して、DCOチェックをpassするようにコミットし直し＆force pushが必要です。

2022-09-09 05:42 UTC, hsgwa requested changes
copyrightとflake8もエラーが残っています。
とりあえず単体テストのエラーだけざっと見ましたが、訂正方法がわからないようであれば声をかけて頂ければと思います。

2022-09-09 05:42 UTC, hsgwa commented on src/test/architecture/test_architecture.py
> +        node_mock = mocker.Mock(spec=NodeStruct)
arch.nodesに対して行われています。
node_mockのto_valueでNodeStructValue返されるようにモック／テストを修正してください。

2022-09-09 05:42 UTC, hsgwa commented on src/test/architecture/test_graph_search.py
> +        pub_info_mock = mocker.Mock(spec=PublisherStruct)
node_mockに関して以下のエラーが表示されています。
![image](https://user-images.githubusercontent.com/19860128/189278814-5871d7e3-32da-4fd1-9bdf-620b6e672d5b.png)
mesage_struct.to_value()が通るように変更をお願いします。

2022-09-09 05:42 UTC, hsgwa commented on src/test/architecture/test_graph_search.py
> +        assert path.to_value() == expected.to_value()
to_valueが未定義で、型チェックに引っかかっています。
to_valueでStructValue型のモックが返されるようにしてください。
![image](https://user-images.githubusercontent.com/19860128/189279088-527f55f4-93b5-4a84-9d3c-9215ad4a6c37.png)

2022-09-09 05:42 UTC, hsgwa commented on src/test/architecture/test_graph_search.py
> +        assert path.to_value() == expected.to_value()
test_single_node_cyclic_caseも同様です。

2022-09-09 06:52 UTC, takam5f2 commented
@hsgwa @rokamu623  
> 今のうちにコメントしておきますと、DCOチェックが失敗しています。
> 本PRが含んでいる全てのコミットに対して、DCOチェックをpassするようにコミットし直し＆force pushが必要です。

DCO -> Details で下の画面が出てくるので、　「Set DCO to pass」 をクリックすると DCO が通る状態になると思います。

![Selection_011](https://user-images.githubusercontent.com/38586589/189289121-e0b6dab5-83dc-44c5-8ba4-aa603b8f82fe.png)

2022-09-12 05:57 UTC, rokamu623 commented on src/test/architecture/test_graph_search.py
> +        pub_info_mock = mocker.Mock(spec=PublisherStruct)
@hsgwa 

NodePathStructの構成を見るとL39
`message_context: Optional[MessageContextStruct]`
でoptional型となっており、L142
`self.message_context.to_value()`
においてNone型に対してto_value()関数を呼び出していることでエラーを吐いていそうです。

pythonのoptional型において、中身がNoneだった場合関数を呼び出さない（Noneをそのまま返す）みたいな構文はありますでしょうか？

2022-09-16 03:14 UTC, rokamu623 commented
単体テストの修正が全て完了しました。

2022-09-16 03:19 UTC, rokamu623 reviewed
@hsgwa 
mypyで確認を行った所、主にこれらの問題があるように思われます。
いずれも実装方針を確認しておきたいです。

2022-09-16 03:19 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
>          return path_searcher.search(*node_names, max_node_depth=max_node_depth)
architecture.py::search_paths()の返り値は
- List[PathStructValue]:
- List[PathStruct]:

のどちらが適格でしょうか？

2022-09-16 03:19 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/callback.py
> +    def to_value(self) -> CallbackStructValue:
抽象クラスをインスタンス化するなという警告を受けているので、CallbackStruct::to_value()を消すか抽象関数にする必要があると思います。

どちらの実装が良いでしょうか？

2022-09-16 03:19 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +    def to_value(self) -> MessageContext:
抽象クラスをインスタンス化するなという警告を受けているので、MessageContextStruct:to_value()を消すか抽象関数にする必要があると思います。

どちらの実装が良いでしょうか？

2022-09-16 05:41 UTC, hsgwa requested changes

2022-09-16 05:41 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
>          return path_searcher.search(*node_names, max_node_depth=max_node_depth)
Architectureクラスのインターフェースは変更しないのが今回の制限ですので、List[PathStructValue]が適切です。

2022-09-16 05:41 UTC, hsgwa commented on src/caret_analyze/architecture/struct/callback.py
> +    def to_value(self) -> CallbackStructValue:
to_valueは必要です。TimerCallbackStructならTimerCallbackStructValue, SubsciptionCallbackStructならSubsciptionCallbackStructValueをインスタンス化してください。

2022-09-16 05:41 UTC, hsgwa commented on src/caret_analyze/architecture/struct/message_context.py
> +    def to_value(self) -> MessageContext:
こちらもCallbackと同様、UseLatesetMessageStructならUseLatesetMessage, ...というように、それぞれに応じたインスタンス化をお願いします。

2022-09-16 05:41 UTC, hsgwa commented on src/test/architecture/test_graph_search.py
> +        pub_info_mock = mocker.Mock(spec=PublisherStruct)
実装は困る所ですが、例えば、_message_context_valueというプロパティを追加し、
その中でNoneならNone,そうでないときだけto_valueを実行したインスタンスを返すようにすると良いと思います。

2022-09-21 01:32 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
>          return path_searcher.search(*node_names, max_node_depth=max_node_depth)
修正しました。

2022-09-21 01:34 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/callback.py
> +    def to_value(self) -> CallbackStructValue:
修正しました。
CallbackStruct::to_value()を直接呼び出すとpassされる実装になっています。

2022-09-21 01:34 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +    def to_value(self) -> MessageContext:
修正しました。
MessageContextStruct:to_value()を直接呼び出すとpassされる実装になっています。

2022-09-21 02:31 UTC, rokamu623 commented
@hsgwa 
自分が変更を加えた部分のmypyエラーは全て除去しました。

2022-09-21 02:40 UTC, rokamu623 reviewed
修正点の一部の説明を記載します。

2022-09-21 02:40 UTC, rokamu623 commented on src/caret_analyze/architecture/util.py
> +    node = Util.find_one(lambda x: x.node_name == node_name, app_arch._nodes)
get_node関数がNodeStructValueを返すが、ここで返してほしいのはNodeStructであったため書き換えました。

2022-09-21 02:40 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +        return True
commitメッセージが変ですがここの意図は、XXXStruct系には.summary()関数がないため.summary()の中身による有功か否かの判断は不要と考え、Trueを返すのみにしました。

2022-09-21 09:15 UTC, hsgwa commented on src/caret_analyze/architecture/util.py
> +    node = Util.find_one(lambda x: x.node_name == node_name, app_arch._nodes)
はい、良いと思います。

2022-09-21 09:18 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +        def is_target_comm(comm: CommunicationStruct):
self.communicationsが入っているので、ココはCommunicationStructValueが入ります。

2022-09-21 09:19 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +    def add_path(self, path_name: str, path_info: PathStruct) -> None:
ここもArchitectureのインターフェースですので、入力は変えず、PathStructValueでお願いします。

2022-09-21 09:19 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +    def update_path(self, path_name: str, path: PathStruct) -> None:
ここもArchitectureのインターフェースですので、入力は変えず、PathStructValueでお願いします。

2022-09-21 09:25 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +    def update_named_path(self, path_name: str, path_info: PathStruct):
ここはArchitectureクラスのインターフェースを変えないようにしたい貯め、PathStructValueが入力になります。

2022-09-21 09:26 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +    def __init__(self, paths: Tuple[PathStruct, ...]) -> None:
NamedPathManagerの各関数のインターフェースはStructValueになります。
NamedPathManagerクラスは入力の型を揃えるために、コンストラクタでもPathStructValueを受け付けるようにしてください。

2022-09-21 09:27 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
>          self._path_manager = NamedPathManager(loaded.paths)
NamedPathManagerのコンストラクタがStructValueになるので、
この引数でloaded.pathsのそれぞれをStructValueに変換したものを引数に与えるようにしてください。

2022-09-21 10:10 UTC, hsgwa commented on src/caret_analyze/architecture/struct/path.py
> +                is_valid = False
verifyは消して頂いて大丈夫です。

2022-09-21 10:10 UTC, hsgwa commented on src/caret_analyze/architecture/struct/subscription.py
> +        return False
Structクラスは__eq__と__hash__は削除お願いします。

2022-09-21 10:12 UTC, hsgwa commented
@rokamu623 
コンフリクトが発生しているので解消もお願いします。

2022-09-26 03:01 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/subscription.py
> +        return False
[fb03050](https://github.com/tier4/CARET_analyze/pull/84/commits/fb030508c31183127b7e25dae11f57406a8c6aad)にて解決しました。

2022-09-26 03:01 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/path.py
> +                is_valid = False
[fb03050](https://github.com/tier4/CARET_analyze/pull/84/commits/fb030508c31183127b7e25dae11f57406a8c6aad)にて解決しました。

2022-09-26 03:01 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +        pass
[fb03050](https://github.com/tier4/CARET_analyze/pull/84/commits/fb030508c31183127b7e25dae11f57406a8c6aad)にて解決しました。

2022-09-26 03:02 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture_exporter.py
> +        # nodes:[]
[fb03050](https://github.com/tier4/CARET_analyze/pull/84/commits/fb030508c31183127b7e25dae11f57406a8c6aad)にて解決しました。

2022-09-26 03:03 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
>          self._path_manager = NamedPathManager(loaded.paths)
[cf777c0](https://github.com/tier4/CARET_analyze/pull/84/commits/cf777c0c1256bed90ff3998db86d84ef714d61de)にて解決しました。

2022-09-26 03:03 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def __init__(self, paths: Tuple[PathStruct, ...]) -> None:
[cf777c0](https://github.com/tier4/CARET_analyze/pull/84/commits/cf777c0c1256bed90ff3998db86d84ef714d61de)にて解決しました。

2022-09-26 03:03 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def update_named_path(self, path_name: str, path_info: PathStruct):
[cf777c0](https://github.com/tier4/CARET_analyze/pull/84/commits/cf777c0c1256bed90ff3998db86d84ef714d61de)にて解決しました。

2022-09-26 03:03 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def add_named_path(self, path_name: str, path_info: PathStruct):
[cf777c0](https://github.com/tier4/CARET_analyze/pull/84/commits/cf777c0c1256bed90ff3998db86d84ef714d61de)にて解決しました。

2022-09-26 03:03 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def update_path(self, path_name: str, path: PathStruct) -> None:
[cf777c0](https://github.com/tier4/CARET_analyze/pull/84/commits/cf777c0c1256bed90ff3998db86d84ef714d61de)にて解決しました。

2022-09-26 03:03 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +    def add_path(self, path_name: str, path_info: PathStruct) -> None:
[cf777c0](https://github.com/tier4/CARET_analyze/pull/84/commits/cf777c0c1256bed90ff3998db86d84ef714d61de)にて解決しました。

2022-09-26 03:03 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +        def is_target_comm(comm: CommunicationStruct):
[cf777c0](https://github.com/tier4/CARET_analyze/pull/84/commits/cf777c0c1256bed90ff3998db86d84ef714d61de)にて解決しました。

2022-09-26 03:06 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/callback.py
> +            None if self.subscribe_topic_name is None else self.publish_topic_names,
[bf11b99](https://github.com/tier4/CARET_analyze/pull/84/commits/bf11b99bb617d335a2ffd9d27cdaa477a226de9b)にて解決しました。
代入する変数（self.subscribe_topic_nameとself.publish_topic_names）を間違えていたケアレスミスだと思います。

2022-09-26 03:06 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/callback.py
> +            '' if self.subscribe_topic_name is None else self.subscribe_topic_name,
[bf11b99](https://github.com/tier4/CARET_analyze/pull/84/commits/bf11b99bb617d335a2ffd9d27cdaa477a226de9b)にて解決しました。

2022-09-26 03:08 UTC, rokamu623 commented
@hsgwa 
上記指摘点の修正、およびそれに伴うflake8の解決と強豪の解決を行いました。

2022-09-26 04:22 UTC, hsgwa commented
まだコードの差分は見ていないですが、pytestがエラーになっています。

nits: 
コミットにはsigned offを付ける習慣を付けていたほうが良いです。
https://kledgeb.blogspot.com/2015/11/ubuntu-git-407-signed-off-bygit-commit.html

2022-09-26 05:47 UTC, hsgwa commented on src/caret_analyze/architecture/struct/message_context.py
> +        pass
@rokamu623 
UseLatestMessageStructにverifyが残っています。

2022-09-26 05:54 UTC, hsgwa commented on src/caret_analyze/architecture/struct/callback.py
> +            None if self.subscribe_topic_name is None else self.publish_topic_names,
修正確認しました。

self.publish_topic_namesは元からOptional[Tuple[str]]なので、if-elseは不要かと思います。
確認をお願いします。

2022-09-26 06:45 UTC, hsgwa requested changes

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/callback.py
> +        Returns the backslash is redundant between brackets
docstringがおかしくなっている気がします。

```suggestion
        Returns
```

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/callback.py
> +            '' if self.subscribe_topic_name is None else self.subscribe_topic_name,
self.subscribe_topic_nameはstrになったので、冗長になっています。
```suggestion
            self.subscribe_topic_name,
```

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/callback.py
> +            None if self.publish_topic_names is None else self.publish_topic_names,
こちらも冗長です
```suggestion
            self.publish_topic_names,
```

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/callback_group.py
> +        callback_group_type_name : str
nit
docstringのParametersが実際の引数と一致していません。
（こちらは元々の実装が一致していなかったです。申し訳ありません。）

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/callback_group.py
> +        callback_values: Tuple[CallbackStruct, ...],
nit
ココは型がValueでなくなったので、変数名はcallbacksが適切です。

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/message_context.py
> +        return self._sub == subscription and self._pub == publisher
こちら、pub側もsub側もto_valueしたクラスで比較をお願いします。

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/message_context.py
> +        return self.callbacks == callbacks
こちらcallbacksはto_valueしたクラスで比較をお願いします。

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/struct/node.py
> +        # node.summary <-  辞書型で要約情報を取得
こちら不要なコメントであれば削除をお願いします。

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/architecture/architecture.py
> +        return tuple(v for v in self._named_paths.values())
ここは冗長です
```suggestion
        return tuple(self._named_paths.values())
```

2022-09-26 06:45 UTC, hsgwa commented on src/caret_analyze/infra/lttng/records_provider_lttng.py
> +<<<<<<< HEAD
ここはコンフリクト解消に失敗しているようです。

2022-09-29 01:42 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/__init__.py
> +# from .qos import Qos
[d20e7f5](https://github.com/tier4/CARET_analyze/pull/84/commits/d20e7f52d6e50606b632ea1bc749c272504accc6)にて修正を行いました。

2022-09-29 01:42 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/__init__.py
> +    'Qos',
[d20e7f5](https://github.com/tier4/CARET_analyze/pull/84/commits/d20e7f52d6e50606b632ea1bc749c272504accc6)にて修正を行いました。

2022-09-29 01:43 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/callback.py
> +        Returns the backslash is redundant between brackets
[d20e7f5](https://github.com/tier4/CARET_analyze/pull/84/commits/d20e7f52d6e50606b632ea1bc749c272504accc6)にて修正を行いました。

2022-09-29 01:43 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/callback.py
> +            None if self.publish_topic_names is None else self.publish_topic_names,
[d20e7f5](https://github.com/tier4/CARET_analyze/pull/84/commits/d20e7f52d6e50606b632ea1bc749c272504accc6)にて修正を行いました。

2022-09-29 01:43 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/callback_group.py
> +        callback_values: Tuple[CallbackStruct, ...],
[d20e7f5](https://github.com/tier4/CARET_analyze/pull/84/commits/d20e7f52d6e50606b632ea1bc749c272504accc6)にて修正を行いました。
データの整合が取れていることを確認済みです。

2022-09-29 01:44 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/node.py
> +        # node.summary <-  辞書型で要約情報を取得
こちらは、自分が追加したコメントではないです。

2022-09-29 01:44 UTC, rokamu623 commented on src/caret_analyze/architecture/architecture.py
> +        return tuple(v for v in self._named_paths.values())
[d20e7f5](https://github.com/tier4/CARET_analyze/pull/84/commits/d20e7f52d6e50606b632ea1bc749c272504accc6)にて修正を行いました。

2022-09-29 01:44 UTC, rokamu623 commented on src/caret_analyze/infra/lttng/records_provider_lttng.py
> +<<<<<<< HEAD
[e77dea4](https://github.com/tier4/CARET_analyze/pull/84/commits/e77dea43dbd40eae7346983f74b1bea86b01aa0c)

2022-09-29 09:46 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +        return self._sub == subscription and self._pub == publisher
[5d5bd56](https://github.com/tier4/CARET_analyze/pull/84/commits/5d5bd567ef238d32997a0f81bbf31e8f54070bc6)及び
6eafcb2にて修正を行いました。
ちょっと実装が汚いかもしれません。

2022-09-29 09:48 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +        return self.callbacks == callbacks
[5d5bd56](https://github.com/tier4/CARET_analyze/pull/84/commits/5d5bd567ef238d32997a0f81bbf31e8f54070bc6)にて修正を行いました。

2022-09-29 10:00 UTC, rokamu623 commented
@hsgwa 
pytest.iniのスペルチェックは、恐らく自分が変更した部分ではないのでここのチェックの解決は保留しています。

2022-09-30 02:16 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +            (None if callbacks is None else [v.to_value() for v in callbacks])
mypyで、Noneをイテレートするなと怒られていたので修正しました。
やっぱり少し実装が汚いです。

2022-09-30 02:30 UTC, hsgwa commented on src/caret_analyze/architecture/struct/message_context.py
> +            (None if callbacks is None else [v.to_value() for v in callbacks])
でしたら、_to_valueを定義してみてはいかがでしょうか？

```
        def _to_value(struct: Optional[CallbackStruct]) -> Optional[CallbackStructValue]:
            if struct:
                return struct.to_value()
            return None
```

2022-09-30 03:11 UTC, hsgwa commented
@rokamu623 
pytest.iniで発生していたスペルチェックエラーについては、下記PRで対応していただきました。
再度spell-check-differentialを動かし、all greenになることを確認済みです。

https://github.com/tier4/autoware-spell-check-dict/pull/359

2022-09-30 08:01 UTC, rokamu623 commented
@hsgwa 
各種テストと、最新のmainとのマージを行いましたので、PRをレビュー可能状態に更新いたします。

2022-09-30 08:43 UTC, hsgwa requested changes
あと少しケアレスミスが残っていました。
こちらも対応をお願いします。

2022-09-30 08:43 UTC, hsgwa commented on src/caret_analyze/architecture/struct/message_context.py
> +        self.message_context_dict = message_context_dict
message_context_dictはprotectedとして_を追加してください
```suggestion
        self._message_context_dict = message_context_dict
```
影響を受ける箇所も修正をお願いします。

2022-10-03 01:21 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +                [v.to_value() for v in structs]
[7c80820](https://github.com/tier4/CARET_analyze/pull/84/commits/7c80820f9ce7401d0d41c085e43b1cae08a9d4b6)にて解決しました。

2022-10-03 01:21 UTC, rokamu623 commented on src/caret_analyze/architecture/struct/message_context.py
> +        self.message_context_dict = message_context_dict
[7c80820](https://github.com/tier4/CARET_analyze/pull/84/commits/7c80820f9ce7401d0d41c085e43b1cae08a9d4b6)にて解決しました。

2022-10-03 01:35 UTC, hsgwa approved these changes
LGTM!

2022-10-03 01:35 UTC, merged