docs: add docstring for Callback Scheduling Visualization
tier4/CARET_analyze pull request #90
Opened 2022-07-19 07:44 UTC by bopeng-saitama

add docstring for Callback Scheduling Visualization

Signed-off-by: Bo Peng <82485734+bopeng-saitama@users.noreply.github.com>

2022-07-21 00:25 UTC, hsgwa requested changes

2022-07-21 00:25 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +        callback gourp instance and the name of target
typoしてます　gourp

2022-07-21 00:25 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +    Get duration range of callback.
ここは実装としてはコールバックの時間を取っていますが、
それでやっていることとしては「get measurement duration」でいかがでしょうか？

2022-07-21 00:25 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +    Get the dataframe of callback which in the target.
この関数はDataFrameではなくColumnDataSourceを返しています。
この関数の説明は訂正をお願いします。

2022-07-21 00:25 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +        the dataframe of callback which in the target
ここもdataframeではなく、data sourceです。

2022-07-21 00:25 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +    Get the dataframe of long rectangular.
同じくDataSourceです。

2022-07-21 00:25 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +        the dataframe of long rectangular
同じくDataSourceです。

2022-07-21 00:25 UTC, hsgwa commented on src/caret_analyze/plot/bokeh/callback_sched.py
> +    Get the callback instances from target and determine the range of visualization.
「  return callbacks」という実装であれば「Get the callback instances」で良いですが、この関数は何も返さないので説明として分かりにくいです。
「コールバックのスケジューリングを可視化する」といった表現ではいかがでしょうか？

2022-07-21 00:25 UTC, hsgwa commented
@bopeng-saitama 遅くなり申し訳ありません。内容についてコメントしたので確認をお願いします。

2022-07-22 03:05 UTC, bopeng-saitama commented
@hsgwa 
修正しました。再チェックををお願いいたします。

2022-07-24 10:08 UTC, hsgwa approved these changes
LGTM!

2022-07-24 10:08 UTC, merged